<?php if ($this->canShowBlock()): ?>
    <?php $_fieldsCollection = $this->getFieldsColection() ?>
    <div class="advfeedback-consultation" id="advfeedback-consultation-holder" style="display:none;">
        <div class="form-title">
            <span
                lang="<?php echo Mage::helper('qmadvfeedback')->getLang() ?>"><?php echo $this->__('Request a Consultation') ?></span>
        </div>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="POST" name="advfeedback-consultation-form"
              id="advfeedback-consultation-form" class="advfeedback-consultation-form">
            <fieldset>
                <?php echo $this->getBlockHtml('formkey'); ?>
                <div class="message" style="display:none;"></div>
                <?php foreach ($_fieldsCollection as $field): ?>
                    <?php if (!$field->getForBot()): ?><div class="row"><?php endif ?>
                        <label for="consultation:<?php echo $field->getName() ?>" class="required"><?php echo $field->getLabel() ?><em>*</em></label>
                        <input type="text" name="consultation[<?php echo $field->getName() ?>]" id="consultation:<?php echo $field->getName() ?>" class="input-text <?php echo $field->getData('additional/class') ?>"/>
                    <?php if (!$field->getForBot()): ?></div><?php endif ?>
                    <?php echo $field->getAfterElementHtml() ?>
                <?php endforeach ?>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Send') ?>" name="send" id="consultation:send">
                        <span><span><?php echo $this->__('Send') ?></span></span>
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        QMAdvancedFeedback.initConsultation({
            isAjax: <?php echo $this->isAjaxEnabled() ?>,
            link: "get-consultation",
            holder: "advfeedback-consultation-holder",
            form: "advfeedback-consultation-form"
        });
        //]]>
    </script>
<?php endif ?>