<?php

$attribute = $this->getAttributeCode();
$prefix = 'layerednavigation-' . $attribute;

$fromValue = $this->getValueFrom();
$toValue   = $this->getValueTo();

$hideCounts = $this->getHideCounts();
?>
<ol <?php if ($this->getCollapsed() && !$this->getHasSelection()): ?>style="display:none" <?php endif ?>>
<?php
$show = ($this->getItemsCount() > 1 || !Mage::getStoreConfig('qm_layerednavigation/general/hide_one_value'));
if (count($this->getItems()) == 1){
    $a  = current($this->getItems());
    if ($a->getLabel() == ''){
        $show = false;
    }
}
?>
<?php if (QM_LayeredNavigation_Model_Catalog_Layer_Filter_Price::DT_DEFAULT == $this->getDisplayType() && $show): ?>
    <?php foreach ($this->getItems() as $_item):?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
            <a class="<?php echo $prefix?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>"<?php if ($this->getSeoRel()) echo ' rel="nofollow"' ?>><?php echo $_item->getLabel() ?></a>
            <?php endif; ?>
            <?php if (!$hideCounts):?>
            (<?php echo $_item->getCount() ?>)
            <?php endif;?>
        </li>
    <?php endforeach ?>
<?php elseif (QM_LayeredNavigation_Model_Catalog_Layer_Filter_Price::DT_DROPDOWN == $this->getDisplayType() && $show): ?>
    <li>
        <select onchange="if (this.value) setLocation(this.value)" class="layerednavigation-select layerednavigation-ajax-select">
            <!-- uncomment to show Filter name in the dropdown <option value=""><?php echo $this->getName() ?></option>-->
            <option value=""></option>
            <?php foreach ($this->getItems() as $_item): ?>
            <option  <?php if (Mage::app()->getRequest()->getParam($attribute) == $_item->getValue()) echo "selected" ?>
                value="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?><?php if (!$hideCounts):?> (<?php echo $_item->getCount() ?>)<?php endif;?></option>
            <?php endforeach ?>
        </select>
    </li>
<?php elseif (QM_LayeredNavigation_Model_Catalog_Layer_Filter_Price::DT_SLIDER == $this->getDisplayType()): ?>
    <li>
        <?php

            $sliderType = $this->getSliderType();

            $max = $this->_filter->getMaxValue();
            $min = $this->_filter->getMinValue();
            if (!$this->getSliderDecimal()){
                $max = ceil($max);
                $min = floor($min);
            }

			if ($this->getSliderDecimal() > 0){
				$max = number_format($max, $this->getSliderDecimal());
				$min = number_format($min, $this->getSliderDecimal());
			}

            /*
             * Holds state of initial price position
             */
            $initialState = false;

            $valueLabel = $this->getValueLabel();
            $valuePlacement = $this->getValuePlacement();

            if (!is_numeric($fromValue)){
                $fromValue = $min;
                $initialState = true;
            }

            /*
             *    User changed price in text boxes
             */
            if ($fromValue <= $min) {
                $initialState = true;
            }

            if (!is_numeric($toValue)) {
                $toValue = $max;
            }

            $from = min($fromValue, $min);
            $to   = max($toValue, $max);

            if ($from < 0.01 && $to < 0.01){
                $to = sprintf('%.00f', $to);
            }

            $decimal = intVal($this->getSliderDecimal());
        ?>

        <?php
        /*
         * Current selection only and With ranges
         */
        if ($sliderType == 0 || $sliderType == 1): ?>
            <div id="<?php echo $prefix?>" class="layerednavigation-slider"
                 data-min="<?php echo $from ?>"
                 data-max="<?php echo $to ?>"
                 data-from-value="<?php echo $fromValue ?>"
                 data-to-value="<?php echo $toValue ?>"
                 data-decimal="<?php echo $decimal ?>"></div>

            <?php
            /*
            * With ranges
            */
            if ($sliderType == 1): ?>
            <div class="layerednavigation-slider-price layerednavigation-slider-price-from"><?php echo $from ?></div>
            <div class="layerednavigation-slider-price layerednavigation-slider-price-to"><?php echo $to ?></div>
            <?php endif ?>
        <?php endif ?>
    </li>
<?php endif; ?>

<?php if ($this->getFromToWidget()):?>
        <?php if (QM_LayeredNavigation_Model_Catalog_Layer_Filter_Price::DT_FROMTO != $this->getDisplayType()):?>
        <li>
            <input type="text" size="2" value="<?php echo $fromValue?>" name="<?php echo $prefix?>" class="input-text" id="<?php echo $prefix?>-from" /> -
            <input type="text" size="2" value="<?php echo $toValue ?>" name="<?php echo $prefix?>" class="input-text" id="<?php echo $prefix?>-to"/>
            <button type="submit" title="<?php echo $this->__('Find')?>" class="form-button button <?php echo $prefix?>-find" name="<?php echo $prefix?>" id="<?php echo $prefix?>-btn"><span><span><?php echo $this->__('Find')?></span></span></button>
        </li>
        <?php endif ?>
<?php else: ?>
    <input type="hidden" size="2" value="<?php echo $fromValue?>"  id="<?php echo $prefix?>-from" />
    <input type="hidden" size="2" value="<?php echo $toValue?>" id="<?php echo $prefix?>-to"/>
<?php endif; ?>
<li style="display:none">
<input type="hidden" id="<?php echo $prefix?>-url" value="<?php echo Mage::helper('qm_layerednavigation/url')->getFullUrl(array($attribute => $prefix . '-from-' . $prefix . '-to'))?>" />
</li>
</ol>