<?php if ($this->helper('qm_devtools')->isRequestAllowed()): ?>
<div class="devtools" id="devtools">
	<a href="" onclick="hide_developer_toolbar(); return false;"><span class="bar_name">Developer Toolbar</span></a>
	<span id="bar_content">
		<a <?php if (Mage::getStoreConfig('dev/debug/template_hints') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/hints/enabled/' . (Mage::getStoreConfig('dev/debug/template_hints') != '1' ? 1 : 0) . '/type/front') ?>">Frontend Hints</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('dev/debug/template_hints', 0) != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/hints/enabled/' . (Mage::getStoreConfig('dev/debug/template_hints', 0) != '1' ? 1 : 0) . '/type/back') ?>">Backend Hints</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('dev/log/active') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/log/enabled/' . (Mage::getStoreConfig('dev/log/active') != '1' ? 1 : 0)) ?>">Logs</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('dev/js/merge_files') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/js/enabled/' . (Mage::getStoreConfig('dev/js/merge_files') != '1' ? 1 : 0)) ?>">Merge JS</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('web/url/use_store') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/url/enabled/' . (Mage::getStoreConfig('web/url/use_store') != '1' ? 1 : 0)) ?>">Store Code in Urls</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('web/seo/use_rewrites') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/seo/enabled/' . (Mage::getStoreConfig('web/seo/use_rewrites') != '1' ? 1 : 0)) ?>">SEO Rewrites</a>
		<span class="seperate"></span>
		<a <?php if (Mage::getStoreConfig('dev/translate_inline/active') != '1') echo ' class="disabled "'; ?> href="<?php echo $this->getUrl('devtools/index/translate/enabled/' . (Mage::getStoreConfig('dev/translate_inline/active') != '1' ? 1 : 0)) ?>">Translate Inline</a>
		<span class="seperate"></span>
		<a style="color:#FF0000;" href="<?php echo $this->getUrl('devtools/index/cache/') ?>">Clean & Disable All Cache</a>
	</span>
</div>
<?php endif; ?>