<?php
$_code = $this->getCode();
?>

<ul class="form-list" id="shipping_form_<?php echo $_code ?>" style="display:none;">
    <li id="city_<?php echo $_code ?>">
        <label><?php echo $this->__('Your City') ?></label>

        <div class="input-box">
            <select data-placeholder="<?php echo $this->__('Select City') ?>" class="select non-storable required-entry"
                    id="select_city_<?php echo $_code ?>"
                    name="shipping_newpost[city_id]">
                <option value=""></option>
            </select>
        </div>
    </li>

    <li id="street_<?php echo $_code ?>">
        <table>
            <tr>
                <th>
                    <label><?php echo $this->__('Your street') ?></label>
                </th>
                <th>
                    <label><?php echo $this->__('Building number') ?></label>
                </th>
                <th>
                    <label><?php echo $this->__('Apartment number') ?></label>
                </th>
            </tr>
            <tr>
                <td>

                    <div class="input-box">
                        <select data-placeholder="<?php echo $this->__('Select Street') ?>"
                                class="select non-storable required-entry street-num"
                                id="select_street_<?php echo $_code ?>"
                                name="shipping_newpost[street_id]" style="display: inline">
                            <option value=""></option>
                        </select>
                    </div>
                </td>
                <td>

                    <div>
                        <input type="text" class="non-storable required-entry building-num"
                               id="text_building_<?php echo $_code ?>"
                               name="shipping_newpost[building_num]">
                        </input>
                    </div>
                </td>
                <td>

                    <div>
                        <input type="text" class="non-storable" id="text_apartment<?php echo $_code ?>"
                               name="shipping_newpost[apartment_num]">
                        </input>
                    </div>
                </td>
            </tr>
        </table>
    </li>

</ul>

<script>
    newPost.registerMethod({
        name: '<?php echo $_code ?>',
        radioId: 's_method_<?php echo $_code ?>_<?php echo $_code ?>',
        wrapperId: 'shipping_form_<?php echo $_code ?>',
        citySelectId: 'select_city_<?php echo $_code ?>',
        cityDataId: 'data_city_<?php echo $_code ?>',
        addressSelectId: 'select_street_<?php echo $_code ?>',
        addressDataId: 'data_street_<?php echo $_code ?>',
        addressWrapperId: 'street_<?php echo $_code ?>'
    });
</script>