<?php $_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price'; ?>
<div class="cart <?php echo $_priceDisplay; ?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Checkout') ?></h1>
        <?php if(!$this->hasError()): ?>
            <ul class="checkout-types top">

            </ul>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>

    <table id="cart-items" class="cart-table data-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1" />
            <col width="1" />
        <?php endif; ?>

        <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
        <thead>
        <tr>
            <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>

            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>

            <th class="a-center cart-price-head" colspan="<?php echo $mergedCells; ?>">
                <!--                            <div class="cart-price-placeholder">-->
                <span class="nobr"><?php echo $this->__('Price') ?></span>
                <!--                            </div>-->
            </th>

            <th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                <?php echo $this->__('Qty') ?>

                <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span>
                        <?php endif*/ ?>

            </th>

            <th class="a-center cart-total-head" colspan="<?php echo $mergedCells; ?>">
                <!--                            <div class="cart-total-placeholder">-->
                <?php echo $this->__('Subtotal') ?>
                <!--                            </div>-->
            </th>

            <th class="a-center" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>

        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif; ?>
        </thead>
        <tfoot>
        <tr>
            <td colspan="50" class="a-right cart-footer-actions">
                <button type="submit" name="update_cart_action" value="update_qty" onclick="setLocation('')" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button2 btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>

                <span class="or">-<?php echo $this->__('or'); ?>-</span>

                <?php if($this->getContinueShoppingUrl()): ?>
                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button2 btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                <?php endif; ?>
                <!--[if lt IE 8]>
                <input type="hidden" id="update_cart_action_container" />
                <script type="text/javascript">
                    //<![CDATA[
                            Event.observe(window, 'load', function()
                            {
                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                $emptyCartButton = $('empty_cart_button');
                                $cartActionContainer = $('update_cart_action_container');
                                if ($emptyCartButton && $cartActionContainer) {
                                    Event.observe($emptyCartButton, 'click', function()
                                    {
                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                        $cartActionContainer.setValue('empty_cart');
                                    });
                                }

                            });
                        //]]>
                        </script>
                        <![endif]-->
            </td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
        </tbody>
    </table>

    <div class="cart-forms">
        <?php echo $this->getChildHtml('qmcheckout_page') ?>
        <?php echo $this->getChildHtml('coupon') ?>
        <?php echo $this->getChildHtml('checkout.cart.extra') ?>
        <?php if (!$this->getIsVirtual()): echo  $this->getChildHtml('qmcheckout_shipping'); endif; ?>
        <?php echo $this->getChildHtml('qmcheckout_payment') ?>
    </div>

    <div class="cart-totals-wrapper">
        <div class="cart-totals">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
                <ul class="checkout-types bottom">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                            <li class="method-<?php echo preg_replace("/[^_a-zA-Z0-9-]/", '-', $method); ?>"><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>