<?php
    $_codeIsApply = strlen($this->getCouponCode());
?>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="total-field">
        <div id="discount-coupon-note" class="note"<?php if ($_codeIsApply): ?>style="display:block;"<?php endif ?>>
            <div class="label">* <?php echo $this->__('Enter your coupon code if you have one.') ?></div>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <input class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
            <?php if ($_codeIsApply): ?>
                <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" name="cancel" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
            <?php else: ?>
                <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button" name="apply" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
            <?php endif; ?>
        </div>
    </div>
</form>