<?php
    $_helper = $this->helper('catalog/output');
    $helper_richsnippets = $this->helper('porto/richsnippets');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
	$headBlock = $this->getLayout()->getBlock('head');

?>
<?php $_product = $this->getProduct(); ?>


<div class="product-video">
	<h3 class="video-block-title"><img src="<?php echo $this->getSkinUrl('images/product/video_01.svg') ?>" alt="<?php echo $this->__('Видео'); ?>"><?php echo $this->__('Video'); ?></h3>
	<div class="yotube-product-video">
		<a href="https://www.youtube.com/watch?v=92Bxzuz7ZH0" rel="prettyPhoto" title="Видео <?php echo $headBlock->getTitle() ?>" class="youtube-link"><img src="https://img.youtube.com/vi/92Bxzuz7ZH0/mqdefault.jpg" alt=""></a>
		<img src="<?php echo $this->getSkinUrl('images/product/youtube_01.svg') ?>" alt="Play video" class="play-video-icon">
	</div>
	<div class="clear"></div>
</div>


<script>

	jQuery(document).ready(function(){

		var $j = jQuery.noConflict();

		var videoWidth = document.body.clientWidth * 0.8;

		if(videoWidth > 1000) videoWidth = 1000;

		var videoHeight = videoWidth / 16 * 9;

		$j("a[rel^='prettyPhoto']").prettyPhoto({
			//iframe_markup: '<iframe src ="{path}" width="{width}" height="{height}" frameborder="no" allowfullscreen></iframe>',
			//iframe_markup: '<iframe src ="{path}" width="{width}" height="{height}" frameborder="no" allowfullscreen></iframe>',
			iframe_markup: '<iframe src ="{path}" width="{width}" height="{height}" frameborder="no" allowfullscreen></iframe>',
			hd: true,
			social_tools: false,
			default_width: videoWidth,
			default_height: videoHeight
		});


	});
</script>

<!--<iframe src="https://www.youtube.com/embed/92Bxzuz7ZH0?rel=1&amp;autoplay=1" width="840" height="472" frameborder="no" allowfullscreen=""></iframe>-->
