<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<div class="cart col-xs-12">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class=" left col-md-6 col-sm-6 col-xs-12">
    <div class="cart-holder">
        <?php echo $this->getChildHtml('qmcheckout_page') ?>
        <?php echo $this->getChildHtml('qmcheckout_shipping') ?>
        <?php echo $this->getChildHtml('qmcheckout_payment') ?>
        <?php echo $this->getChildHtml('checkout.cart.extra') ?>
    </div>
    </div>
    <div class=" right col-md-6 col-sm-6 col-xs-12">
    <div class="cart-sidebar">
        <div class="cart-sidebar-holder">
            <?php echo $this->getChildHtml('form_before') ?>
            <ul class="cart-items" id="cart-items">
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
            </ul>
            <div class="totals">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                        <?php foreach ($this->getMethods('methods') as $method): ?>
                            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                                <li><?php echo $methodHtml; ?></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </div>
            <?php echo $this->getChildHtml('coupon') ?>
        </div>
    </div>
    </div>
    <div class="clear"></div>
    <div class="cart-collaterals">
        <?php echo $this->getChildHtml('crosssell') ?>
    </div>
</div>