<?php if ($this->canShowBlock()): ?>
<div class="oneclickorder-order" id="oneclickorder-order-holder" style="display:none;">
    <div class="form-title">
        <h3><?php echo $this->__('One click order') ?></h3>
    </div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="POST" name="oneclickorder-order-form" id="oneclickorder-order-form" class="oneclickorder-order-form">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <input type="hidden" name="order[product_id]" value="<?php echo $this->getCurrentProductId() ?>">
            <div class="message no-display"></div>
            <?php if ($this->canShowName()): ?>
            <div class="row">
                <label for="order:name" class="required"><?php echo $this->__('Name') ?></label>
                <input type="text" name="order[name]" id="order:name" class="input-text required-entry"/>
            </div>
            <?php endif ?>
            <?php if ($this->canShowEmail()): ?>
                <div class="row">
                    <label for="order:email" class="required"><?php echo $this->__('Email') ?></label>
                    <input type="text" name="order[email]" id="order:email" class="input-text required-entry validate-email"/>
                </div>
            <?php endif ?>
            <?php if ($this->canShowTelephone()): ?>
            <div class="row">
                <label for="order:telephone" class="required"><?php echo $this->__('Telephone') ?></label>
                <input type="text" name="order[telephone]" id="order:telephone" class="input-text required-entry validate-phone380"/>
            </div>
            <script type="text/javascript">
            //<![CDATA[
                jQuery(function($){$("#order\\:telephone").mask("+38(099)999-99-99")});
            //]]>
            </script>
            <?php endif ?>
            <?php if ($this->canShowComment()): ?>
            <div class="row">
                <label for="order:comment"><?php echo $this->__('Comment') ?></label>
                <textarea name="order[comment]" id="order:comment" class="input-text" cols="30" rows="5"></textarea>
            </div>
            <?php endif ?>
            <div class="buttons-set">
                <button type="submit" class="button" title="<?php echo $this->__('Place Order') ?>" name="send" id="order:place">
                    <span><span><?php echo $this->__('Place Order') ?></span></span>
                </button>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    QMOneclickOrder.initOrder({
        isAjax: <?php echo $this->isAjaxEnabled() ?>,
        placeButtonText: "<?php echo $this->__('Buy now with 1 Click') ?>",
        holder: "oneclickorder-order-holder",
        form: "oneclickorder-order-form",
        insertSelector: "<?php echo $this->getInsertButtonSelector() ?>"
    });
//]]>
</script>
<?php endif ?>