<?php

/**
 * Banner view widget template
 *
 * @category    QM
 * @package     QM_Banners
 * @author      Ultimate Module Creator
 */
?>
<?php $_banner = $this->getCurrentBanner(); ?>

<?php if ($_banner && $_banner->getCssStyle()) : ?>
    <style type="text/css"><?php echo $_banner->getCssStyle() ?></style>
<?php endif; ?>

<?php if ($_banner && $_banner->getRenderedHtml()) : ?>
    <div class="qm_banner_wrapper <?php echo $_banner->getCssClass() ?>"
         style="<?php if($_banner->getWidth()): ?>width:<?php echo $_banner->getWidth() ?>; <?php endif ?> <?php if($_banner->getHeight()): ?>height:<?php echo $_banner->getHeight() ?>;<?php endif ?>">
        <?php echo $_banner->getRenderedHtml() ?>
    </div>
<?php endif; ?>
